import Link from 'next/link';
import '../styles/global.css';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <title>Next.js 13 | Piratechs</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <header>
          <Link className={`hoverLink`} href={`/`}>Next.js</Link>
          <Link className={`hoverLink`} href={`/about`}>About</Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
